routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();

Route::post('/passwordReset', 'UserController@passwordReset')->name('passwordReset');
Route::get('/passwordResetView', 'UserController@passwordResetView')->name('passwordResetView');
Route::get('/userHome', 'UserController@userHome')->name('userHome');

Route::group(['middleware' => 'auth'], function () {

    Route::resource('user', 'UserController', ['except' => ['show']]);

    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

    Route::post('filter', 'ClientController@filter')->name('filter');
    Route::resource('client', 'ClientController', ['except' => ['show']]);

    Route::resource('city', 'CityController', ['except' => ['show']]);
});

app/Models/City.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    protected $fillable = [
        'id', 'cod', 'name', 'created_at', 'updated_at'
    ];

    public function client()
    {
        return $this->hasOne(Client::class);
    }
}

app/Http/Controllers/CityController.php
<?php

namespace App\Http\Controllers;

use App\Models\City;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;
use Exception;

class CityController extends Controller
{
    /**
     * Display a listing of the resource.
     * Llamado de todas las ciudades, paginadas en grupos de a 5.
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cities = City::paginate(5);
        return view('cities.index', ['cities' => $cities]);
    }

    /**
     * Show the form for creating a new resource.
     *Llamado a la vista del formulario de creación de una ciudad
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cities.create');
    }

    /**
     * Store a newly created resource in storage.
     * Método de creación de una ciudad: parametros cod y name obligatorios.
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'cod' => 'required',
            'name' => 'required'
        ]);

        if ($validator->fails()) {
            return ($validator->errors());
        }

        try {
            $city = new City;
            $city = $city->create($request->all());
        } catch (Exception $e) {
            return redirect()->route('city.index')->withStatus(__($e->getMessage()));
        }
        return redirect()->route('city.index')->withStatus(__('Ciudad creada con éxito.'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\City  $city
     * @return \Illuminate\Http\Response
     */
    public function show(City $city)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     * Método para el llamado de un formulario de edición de una ciudad
     * @param  \App\Models\City  $city
     * @return \Illuminate\Http\Response
     */
    public function edit(City $city)
    {
        return view('cities.edit', ['city' => $city]);
    }

    /**
     * Update the specified resource in storage.
     * Método de actualización de una ciudad , con parametros cod y name obligatorios.
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\City  $city
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, City $city)
    {
        $validator = Validator::make($request->all(), [
            'cod' => 'required',
            'name' => 'required',
        ]);

        if ($validator->fails()) {
            return ($validator->errors());
        }

        try {
            $city->update($request->all());
        } catch (Exception $e) {
            return redirect()->route('city.index')->withStatus(__($e->getMessage()));
        }
        return redirect()->route('city.index')->withStatus(__('Ciudad Actualizada con éxito.'));
    }

    /**
     * Remove the specified resource from storage.
     * Método de eliminación de una ciudad
     * @param  \App\Models\City  $city
     * @return \Illuminate\Http\Response
     */
    public function destroy(City $city)
    {
        $city->delete();
        return redirect()->route('city.index')->withStatus(__('Ciudad eliminada con éxito.'));
    }
}

resources/views/cities/create.blade.php
@extends('layouts.app', ['title' => __('Crean Ciudad')])

@section('content')
    @include('users.partials.header', ['title' => __('Creación de ciudades')])
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Lista de ciudades') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('city.index') }}" class="btn btn-sm btn-primary">{{ __('Volver a la lista') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('city.store') }}" autocomplete="off">
                            @csrf

                            <h6 class="heading-small text-muted mb-4">{{ __('Informacion del bien') }}</h6>
                            <div class="pl-lg-4">

                                <div class="form-group{{ $errors->has('cod') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Código') }}</label>
                                    <input type="text" name="cod" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Código') }}" value="{{ old('cod') }}" required autofocus>

                                    @if ($errors->has('cod'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('cod') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Nombre') }}</label>
                                    <input type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Nombre') }}" value="{{ old('name') }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Guardar') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/cities/edit.blade.php
@extends('layouts.app', ['title' => __('Actualizacion de ciudad')])

@section('content')
    @include('users.partials.header', ['title' => __('Actualizar ciudad')])

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Lista de ciudades') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('city.index') }}" class="btn btn-sm btn-primary">{{ __('Volver a lalista') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('city.update', $city) }}" autocomplete="off">
                            @csrf
                            @method('put')
                            <h6 class="heading-small text-muted mb-4">{{ __('Informacion del ciudad') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('cod') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Código') }}</label>
                                    <input type="text" name="cod" id="input-name" class="form-control form-control-alternative{{ $errors->has('cod') ? ' is-invalid' : '' }}" placeholder="{{ __('Cod') }}" value="{{ old('cod', $city->cod) }}" required autofocus>

                                    @if ($errors->has('cod'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('cod') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Nombre') }}</label>
                                    <input type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Name') }}" value="{{ old('name', $city->name) }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Guardar') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/cities/index.blade.php
@extends('layouts.app', ['title' => __('Lista de ciudades')])

@section('content')
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row">

                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Ciudades') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('city.create') }}" class="btn btn-sm btn-primary">{{ __('Crear ciudad') }}</a>
                            </div>
                        </div>
                    </div>

                    <div class="col-12">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('status') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>

                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">{{ __('Cod') }}</th>
                                    <th scope="col">{{ __('Nombre') }}</th>
                                    <th scope="col">{{ __('Fecha de creación') }}</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($cities as $city)
                                    <tr>
                                        <td>{{ $city->cod }}</td>
                                        <td>{{ $city->name }}</td>
                                        <td>{{ $city->created_at->format('d/m/Y H:i') }}</td>
                                        <td class="text-right">
                                            <div class="dropdown">
                                                <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="fas fa-ellipsis-v"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                        <form action="{{ route('city.destroy', $city) }}" method="post">
                                                            @csrf
                                                            @method('delete')
                                                            <a class="dropdown-item" href="{{ route('city.edit', $city) }}">{{ __('Actualizar') }}</a>
                                                            <button type="button" class="dropdown-item" onclick="confirm('{{ __(" Estás seguro de que deseas eliminar a este ciudad?") }}') ? this.parentElement.submit() : ''">
                                                                {{ __('Eliminar') }}
                                                            </button>
                                                        </form>

                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer py-4">
                        <nav class="d-flex justify-content-end" aria-label="...">
                            {{ $cities->links() }}
                        </nav>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection