routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();

Route::post('/passwordReset', 'UserController@passwordReset')->name('passwordReset');
Route::get('/passwordResetView', 'UserController@passwordResetView')->name('passwordResetView');
Route::get('/userHome', 'UserController@userHome')->name('userHome');

Route::group(['middleware' => 'auth'], function () {

    Route::resource('user', 'UserController', ['except' => ['show']]);

    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

    Route::post('filter', 'ClientController@filter')->name('filter');
    Route::resource('client', 'ClientController', ['except' => ['show']]);

    Route::resource('city', 'CityController', ['except' => ['show']]);
});

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $fillable = [
        'id', 'cod', 'name', 'city_id'
    ];

    public function city()
    {
        return $this->belongsTo(City::class);
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Models\City;
use App\Models\Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;
use Exception;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     * Llamado de todas los clientes, paginadas en grupos de a 5. Adicional cuenta con el filtro de ciudades
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $clients = Client::with('city')
        ->when($request->city_id, function ($query) use ($request) {
            return $query->where('city_id', $request->city_id);
        })
        ->paginate(5);
        $cities = City::all();
        return view('clients.index', ['clients' => $clients, 'cities' => $cities]);
    }

    /**
     * Show the form for creating a new resource.
     *Llamado a la vista del formulario de creación de un cliente
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cities = City::all();
        return view('clients.create', ['cities' => $cities]);
    }

    /**
     * Store a newly created resource in storage.
     * Método de creación de un cliente: parametros cod,name y city_id obligatorios.
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'cod' => 'required',
            'name' => 'required',
            'city_id' => 'required|numeric',
        ]);

        if ($validator->fails()) {
            return ($validator->errors());
        }
        try {
            $client = new Client;
            $client = $client->create($request->all());
        } catch (Exception $e) {
            return redirect()->route('client.index')->withStatus(__($e->getMessage()));
        }
        return redirect()->route('client.index')->withStatus(__('Cliente creado con éxito.'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *Llamado a la vista del formulario de actualización de un cliente
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        $cities = City::all();
        return view('clients.edit', ['client' => $client, 'cities' => $cities]);
    }

    /**
     * Update the specified resource in storage.
     * Método de actualización de un cliente: parametros cod,name y city_id obligatorios.
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        $validator = Validator::make($request->all(), [
            'cod' => 'required',
            'name' => 'required',
            'city_id' => 'required|numeric',
            'updated_at' => 'nullable|date'
        ]);

        if ($validator->fails()) {
            return ($validator->errors());
        }

        try {
            $client->update($request->all());
        } catch (Exception $e) {
            return redirect()->route('client.index')->withStatus(__($e->getMessage()));
        }
        return redirect()->route('client.index')->withStatus(__($e->getMessage()));
    }

    /**
     * Remove the specified resource from storage.
     * Método de eliminación de un cliente
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        $client->delete();
        return redirect()->route('client.index')->withStatus(__('Cliente eliminado con éxito.'));
    }
}

resources/views/clients/create.blade.php
@extends('layouts.app', ['title' => __('Crean Cliente')])

@section('content')
    @include('users.partials.header', ['title' => __('Creación de clientes')])
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Lista de clientes') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('client.index') }}" class="btn btn-sm btn-primary">{{ __('Volver a la lista') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('client.store') }}" autocomplete="off">
                            @csrf

                            <h6 class="heading-small text-muted mb-4">{{ __('Informacion del cliente') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('cod') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Código') }}</label>
                                    <input type="text" name="cod" id="input-name" class="form-control form-control-alternative{{ $errors->has('cod') ? ' is-invalid' : '' }}" placeholder="{{ __('Código') }}" value="{{ old('cod') }}" required autofocus>

                                    @if ($errors->has('cod'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('cod') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Nombre') }}</label>
                                    <input type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Nombre') }}" value="{{ old('name') }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="form-group{{ $errors->has('value') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-value">{{ __('Ciudad') }}</label>
                                    <select name="city_id" id="city_id" required class="form-control">
                                        <option value="">Seleccione una ciudad</option>
                                        @foreach ($cities as $item)
                                        <option value="{{$item->id}}">{{$item->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Guardar') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/clients/edit.blade.php
@extends('layouts.app', ['title' => __('Actualizacion de cliente')])

@section('content')
    @include('users.partials.header', ['title' => __('Actualizar cliente')])

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Lista de clientes') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('client.index') }}" class="btn btn-sm btn-primary">{{ __('Volver a lalista') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('client.update', $client) }}" autocomplete="off">
                            @csrf
                            @method('put')
                            <h6 class="heading-small text-muted mb-4">{{ __('Informacion del cliente') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('cod') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Código') }}</label>
                                    <input type="text" name="cod" id="input-name" class="form-control form-control-alternative{{ $errors->has('cod') ? ' is-invalid' : '' }}" placeholder="{{ __('Cod') }}" value="{{ old('cod', $client->cod) }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Nombre') }}</label>
                                    <input type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Name') }}" value="{{ old('name', $client->name) }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('value') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-value">{{ __('Ciudad') }}</label>
                                    <select name="city_id" id="city_id" required class="form-control">
                                        <option value="">Seleccione una ciudad</option>
                                        @foreach ($cities as $item)
                                        <option value="{{$item->id}}">{{$item->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <!--<div class="form-group{{ $errors->has('description') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-description">{{ __('Descripción') }}</label>
                                    <textarea rows="4" cols="50" type="text" name="description" id="input-description" class="form-control form-control-alternative{{ $errors->has('description') ? ' is-invalid' : '' }}" placeholder="{{ __('Descripción') }}" value="{{ old('description', $client->description) }}" required autofocus>{{$client->description}}
                                        </textarea>
                                    @if ($errors->has('description'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('description') }}</strong>
                                        </span>
                                    @endif
                                </div>-->

                                <!--<div class="form-group{{ $errors->has('value') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-value">{{ __('Valor') }}</label>
                                    <input type="number" name="value" id="input-value" class="form-control form-control-alternative{{ $errors->has('value') ? ' is-invalid' : '' }}" placeholder="{{ __('Valor') }}" value="{{ old('value',$client->value) }}" required>

                                    @if ($errors->has('value'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('value') }}</strong>
                                        </span>
                                    @endif
                                </div>-->

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Guardar') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/clients/filter.blade.php
<div class="row align-items-center">
    <form method="get" action="{{ route('client.index') }}" autocomplete="off">
        <div class="col-10 text-left">
            <select name="city_id" id="city_id" required class="form-control" class="small">
                <option value="">Seleccione una ciudad</option>
                @foreach ($cities as $item)
                <option value="{{$item->id}}">{{$item->name}}</option>
                @endforeach
            </select>
        </div>
        <div class="col-2 text-left">
            <button type="submit" class="btn btn-success mt-4">{{ __('Filtrar') }}</button>
        </div>
    </form>
</div>

resources/views/clients/index.blade.php
@extends('layouts.app', ['title' => __('Lista de Clientes')])

@section('content')
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row">

                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Clientes') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('client.create') }}" class="btn btn-sm btn-primary">{{ __('Crear Cliente') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-header border-0">
                        @include('clients.filter')
                    </div>

                    <div class="col-12">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('status') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>

                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">{{ __('Código') }}</th>
                                    <th scope="col">{{ __('Nombre') }}</th>
                                    <th scope="col">{{ __('Ciudad') }}</th>
                                    <th scope="col">{{ __('Fecha de creación') }}</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($clients as $client)
                                    <tr>
                                        <td>{{ $client->cod }}</td>
                                        <td>{{ $client->name }}</td>
                                        <td>{{ $client->city->name }}</td>
                                        <td>{{ $client->created_at->format('d/m/Y H:i') }}</td>
                                        <td class="text-right">
                                            <div class="dropdown">
                                                <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="fas fa-ellipsis-v"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                        <form action="{{ route('client.destroy', $client) }}" method="post">
                                                            @csrf
                                                            @method('delete')
                                                            <a class="dropdown-item" href="{{ route('client.edit', $client) }}">{{ __('Actualizar') }}</a>
                                                            <button type="button" class="dropdown-item" onclick="confirm('{{ __(" Estás seguro de que deseas eliminar a este Cliente?") }}') ? this.parentElement.submit() : ''">
                                                                {{ __('Eliminar') }}
                                                            </button>
                                                        </form>

                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer py-4">
                        <nav class="d-flex justify-content-end" aria-label="...">
                            {{ $clients->links() }}
                        </nav>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection